// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "HandWriting",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "HandWriting",
            targets: ["AppModule"],
            bundleIdentifier: "com.nikechukwu.HandWriting",
            teamIdentifier: "54S7P6J45Q",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Data/Assets"),
                .process("./Fonts"),
            ]
        )
//        .testTarget(
//            name: "AppModuleTests",
//            dependencies: ["AppModule"],
//            path: "Tests"
//        )
    ],
    swiftLanguageVersions: [.version("6")]
)
