// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HandWriting",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "HandWriting",
            targets: ["AppModule"],
            bundleIdentifier: "com.nikechukwu.HandWriting",
            teamIdentifier: "54S7P6J45Q",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-testing.git", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Testing", package: "swift-testing")
            ],
            path: ".",
            resources: [
                .process("Data/Assets")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)