# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: App Build and Test

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
    - name: Install JSON Package
      run: |
        # pip install jsonschema'[format]'
        pipx install check-jsonschema
    # - name: Validate JSON
    #   run: check-jsonschema --schemafile levels.schema.json levels.json
    #   working-directory: ./Data/Assets
    - name: Build App
      run: swift build -v
    - name: Run tests on app
      run: swift test -v
